package fbp

/* /home/tyoung3/go/mod/fbp/fbp_test.go
 *		 	 DO NOT EDIT!!!
 *		generated by fbpgo.sh-v0.0.1  on Wed May  8 15:47:10 EDT 2019
**/

import "testing"
import "sync"

func dummyComponent2(wg *sync.WaitGroup,
	arg []string,
	cs []chan interface{}) {
	defer wg.Done()
	close(cs[0])
}

func TestLaunch(t *testing.T) {
	var cs2 []chan interface{}
	var wg sync.WaitGroup

	arg := []string{"x2"}
	// done2 := make(chan struct{})
	cs2 = append(cs2, make(chan interface{}))
	Launch(&wg, arg, dummyComponent2, cs2)
	wg.Wait()

}
