package strings

/* /home/tyoung3/go/mod/fbp/comp1/comp1.go
 *		 	 DO NOT EDIT!!!
 *		generated by fbpgo.sh-v0.0.1  on Wed May  8 15:47:10 EDT 2019
**/

import "fmt"
import "sync"
import "strconv"

var Version string ="0.0.0" 

func Comp1(wg *sync.WaitGroup, arg []string, cs []chan interface{}) {
	var n0 int = 7
	var n int

	defer wg.Done()
	//pname := arg[0]
	l := len(arg)
	if l > 1 {
		n0, _ = strconv.Atoi(arg[1])
	}

	c := cs[0]

	for n = 1; n < n0+1; n++ {
		c <- fmt.Sprintf("%s-%d", arg[0], n)
	}

	close(c)
}
