package strings

/* /home/tyoung3/go/mod/fbp/comp2/comp2_test.go
 *		 	 DO NOT EDIT!!!
 *		generated by fbpgo.sh-v0.0.1  on Wed May  8 15:47:11 EDT 2019
**/

import "testing"
import "fmt"
import "sync"

func TestComp2(t *testing.T) {
	var cs []chan interface{}
	var wg sync.WaitGroup
	arg := []string{"TestComp2", "xx"}

	fmt.Println("TestComp2")
	cs = append(cs, make(chan interface{}))
	c := cs[0]

	go func() {
		c <- 7
		c <- 11
		c <- "OK?"
		close(c)
	}()

	wg.Add(1)
	go Comp2(&wg, arg, cs)
	fmt.Println("TestComp2 wait c ")
	wg.Wait()
	fmt.Println("TestComp2 done.")
}
