/* package edit is generated by StreamWork.*/
package edit

/*  Generated StreamWork component, Controller,
    by sw.sh on Wed Jun 26 20:00:23 EDT 2019
	2  input  ports
	2 output ports
*/

import (
	"fmt"
	"sync"
)

/* Channel 0 Input from view 
   CHannel 1 Input from ModelView
   Channel 2 Output to view
   Channel 3 Output to ModelVies	
*/
func Controller(wg *sync.WaitGroup, arg []string, cs []chan interface{}) {

	defer wg.Done()
	cfg := pkgConfig("/home/tyoung3/.sw/edit.toml")
	seqno, _ := cfg.IntOr("edit.seqno", 1)
	bs, _ := cfg.IntOr("edit.buffersize", 1)
	fmt.Println(
		"Running", arg[0], version, "bs =", bs)

	if seqno < 50 || seqno > 10000 {
		fmt.Println(
			"Seqno < 50 or > 10000.  Missing config file?")
	}

	i := 3

	for i >= 2 {
		cs[i] <- i
		close(cs[i])
		i--
	}

	j := 1
	for j >= 0 {
			ip, ok := <-cs[j]
			if ok != true {
				break
			}
			fmt.Println(arg[0], "chan:", j, "IP:", ip)
		j--
	}
}
