/* package edit is generated by StreamWork.*/
package edit

/*  Generated StreamWork component, ModelView,
    by sw.sh on Wed Jun 26 20:00:48 EDT 2019
	2  input  ports
	2 output ports
*/

import (
	"fmt"
	"sync"
)

func ModelView(wg *sync.WaitGroup, arg []string, cs []chan interface{}) {

	defer wg.Done()
	cfg := pkgConfig("/home/tyoung3/.sw/edit.toml")
	bs, _ := cfg.IntOr("edit.buffersize", 1)
	fmt.Println(
		"Running", arg[0], version, "bs =", bs)


	j := 1
	for j >= 0 {
			ip, ok := <-cs[j]
			if ok != true {
				break
			}
			fmt.Println(arg[0], "chan:", j, "IP:", ip)
		j--
	}
	i := 3

	for i >= 2 {
		cs[i] <- i
		close(cs[i])
		i--
	}
}
